### ISSUE TITLE
Add dotnet tool support the Generator

### ISSUE THREAD

**Issue by EifelMono** [dotMorten/DotNetOMDGenerator#21]
Add dotnet tool support,
so anybody can use it directly after installation from nuget from the shell.

https://docs.microsoft.com/de-de/dotnet/core/tools/dotnet-tool-install

Hier is a list with of other dotnet tools
https://github.com/natemcmaster/dotnet-tools

**Comment by dotMorten** [comment]
@eifelmono good idea! I'll get on it

**Comment by dotMorten** [comment]
Done!
```
dotnet tool install --global dotMorten.OmdGenerator
generateomd /assemblies=myassembly.dll
```
