### ISSUE TITLE
Add grouping support to HTML OMD

### ISSUE THREAD

**Issue by dotMorten** [dotMorten/DotNetOMDGenerator#4]
It would be useful to be able to quickly group/reorder objects by namespaces.

**Comment by IanMercer** [comment]
Might be worth changing the default sort order to Namespace then Name. 
       `symbols = symbols.OrderBy(t => t.GetFullTypeName()).ToList();`

But adding a Namespace header / divider and an expando-collapso widget for the HTML output would be good too.

**Comment by dotMorten** [comment]
I agree. Updated the sorting and added the divider. See example here: http://www.sharpgis.net/Tests/corefx.html

**Comment by IanMercer** [comment]
Nice!

**Comment by Odonno** [comment]
@dotMorten I was thinking about reusing the user-friendly design of the MSDN you can find here: https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.calls.callanswereventargs

At least, the left sidebar that give you the possibility:

* to filter namespace (and eventually class names, properties, methods, ...)
* to group by namespace
* and maybe group by sub-namespace (subgroup)
* that give you quick access (scrolling) to a namespace when you click on it

**Comment by dotMorten** [comment]
Closing specific issue since types are now grouped by namespaces, and @skendrot added support for collapsing them
