### ISSUE TITLE
Add support for XML comments

### ISSUE THREAD

**Issue by IanMercer** [dotMorten/DotNetOMDGenerator#7]
Would be nice if XML comments could flow through to the HTML, maybe as tooltips on each of the elements.

**Comment by dotMorten** [comment]
They already do! I did notice Edge sometimes struggle with showing them.

**Comment by IanMercer** [comment]
But maybe an option to include them in the visible HTML.

**Comment by dotMorten** [comment]
@IanMercer I would have no clue how to do that and still make the OMD readable. This isn't API documentation. It's an OMD.
