### ISSUE TITLE
Suggestion: Sort the properties and methods by name and the constructors by # of parameters

### ISSUE THREAD

**Issue by IanMercer** [dotMorten/DotNetOMDGenerator#9]
May be a nice enhancement to sort the constructors by number of parameters and the properties and methods by name.

    foreach (var method in type.GetConstructors(oldType).OrderBy(m => m.Item1.Parameters.Count()))
    foreach (var method in type.GetProperties(oldType).OrderBy(m => m.Item1.Name))
    etc.

**Comment by dotMorten** [comment]
Can't believe I didn't even notice that until now. Now my eyes hurt! On it!
